=== jayvikramsharma1/jvs/mat-dashboard/schema/testcase.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT testCase (steps)>
<!ATTLIST testCase name CDATA #REQUIRED>
<!ATTLIST testCase comments CDATA #REQUIRED>
<!ELEMENT steps (step+)>
<!ELEMENT step (inputs*, expected*)>
<!ATTLIST step name CDATA #REQUIRED>
<!ATTLIST step require (Login|MoD|PagePlanner|Publication|EditorialPlan|TemplatePlan|NewStory|SaveStory|ChannelCopy|ArticlePreparation|QuickMetadataTablet|AssertInsertInline|NewSearchQuery|PagePlannerMetadata|ArticleImageMetadata|Formatting|EditorialWorkFlow|Hyperlink|TabPageFlow|CHP|SendToProduction|CHPFolder|InsertPages|PropertyWindow|SectionMetatadata|VideoStory|EditorialLogin|STEditionCreation|Confirmation) #REQUIRED>
<!ATTLIST step method CDATA #REQUIRED>
<!ATTLIST step screenshot (true|false) #IMPLIED>
<!ELEMENT inputs (input*)>
<!ELEMENT input EMPTY>
<!ATTLIST input value CDATA #REQUIRED>
<!ATTLIST input type (INTEGER|STRING|BOOLEAN) #REQUIRED>
<!ELEMENT expected (result*)>
<!ELEMENT result EMPTY>
<!ATTLIST result message CDATA #REQUIRED>
<!ATTLIST result value CDATA #REQUIRED>
<!ATTLIST result type (S3|WINDOW) #REQUIRED>
<!ATTLIST result feedType (edition|book|section|slot|article|image|articleMetadata|slotMetadata|imageMetadata|imagePositional) #REQUIRED>
<!ATTLIST result s3Content (true|false) #IMPLIED>
<!ATTLIST result element CDATA #REQUIRED>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/positional_vertical_align.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="PositionalVerticalAlign" >
	<steps>
		<step name="slotSelection" method="slot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="BS_positional_vertical_align_Story_5*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
			<step name="preparingtheArticle" method="storyPreparationCHP"
			require="ArticlePreparation">
			<inputs>
			<input value="Positional vertical Alignment" type="STRING" />
				<input value="Automation Standfirst" type="STRING" />
				<input value="Automation onecolumnStandfirst" type="STRING" />
				<input value="Automation floorlineHeadline" type="STRING" />
			</inputs>
		</step>
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_positional_vertical_align_image_5*" type="STRING" />
			</inputs>
		</step>
		<!-- <step name="saveandPublishtheArticle" method="publishArticle"
			require="ArticlePreparation" /> -->
		<step name="imageMetadata" method="clickingOnImage" require="ArticlePreparation">
		</step>
		<step name="SettingtheColumnwidth" method="positionalsVerticalAlign"
			require="ArticleImageMetadata">
			<inputs>
				<input value="1" type="INTEGER" />
			</inputs>
		</step>
		<step name="ClickSavebutton" method="medataPanelSaveBtn" require="ArticleImageMetadata">
		</step>
		<step name="closeStoryPreparation" method="gettingImageUUID"
			require="ArticlePreparation">
		</step>
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<!-- <step name="navigatingtoTabPageFlow" method="releasePage"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="clickingontheStatus" method="tabPageFlow" require="TabPageFlow">
			<inputs>
				<input value="3" type="INTEGER" />
			</inputs>
		</step>
		<step name="navigatingtoWorkFlowWindow" method="workflowIrish"
			require="EditorialPlan" />
		<step name="ChangingStatustoDone" method="editorialPlanDoneStatus"
			require="EditorialWorkFlow" /> -->
		<step name="publishtheSlot" method="publish" require="EditorialPlan">
			<expected>
				<result message="Image vertical Allignment" value="top"
					element="cpi:anchor" type="S3" feedType="imagePositional" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/font_size.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="HeadlineFontSize"
	comments="Executing testcase in Main Book in Register section Slot1">
	<steps>
		<!-- <step name="moveDowntoNewsSlot" method="editorialPageDown" require="EditorialPlan"> 
			<inputs> <input value="down" type="STRING" /> <input value="20" type="INTEGER" 
			/> </inputs> </step> -->
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_FontSize*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_FontSize*" type="STRING" />
			</inputs>
		</step>
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan" />
		<step name="OpenTheSelectedSlotAgaintoChangeTheArtilcleHeadlineSize"
			method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="openTheStory" method="open_article" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="saveTheArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" >
			</step>
	<step name="clickOnHeadline" method="clickOnTitleHeadline"
			require="ArticlePreparation" screenshot="true">
		</step>
		<step name="enterFontSize" method="fontSize" require="Formatting"
			screenshot="true">
			<inputs>
				<input value="5rem" type="STRING" />
			</inputs>
		</step>
		<step name="SaveFontSize" method="formattingSaveBtn" require="Formatting" /> 
		<step name="closetheArticlePreparationPagewithArticleChange"
			method="closeArticlePreparation" require="ArticlePreparation" />
		<step name="closetemplatepagewithUpdateArticle" method="close_window"
			require="TemplatePlan" />
		<step name="republishTheSlot" method="publish" require="EditorialPlan">
			<expected>
				<result message="Font Size should be 5 rem" value="span" element="//cpi:headline/xhtml:div/xhtml:span[@style='font-size: 5rem; display: inline-block;']"
					type="S3" feedType="article" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/ps_791.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="ps791">
		<steps>
		<step name="slotSelection" method="slot" require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="insertStory" method="create_article" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="clickCreateStoryBtn" method="storyCreateBtn" require="NewStory" />
		<step name="articleName" method="fileName" require="SaveStory">
			<inputs>
				<input value="BS_Deeplink01" type="STRING" />
			</inputs>
		</step>
		<step name="clickSaveAsBtn" method="saveasBtn" require="SaveStory" />
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="performChannelCopy" method="createChannelCopy"
			require="ChannelCopy" />
		<step name="ScrollToInline" method="mousewheeler" require="ArticlePreparation">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
			</inputs>
		</step>
		<step name="setFont" method="setFont" require="ArticlePreparation">
			<inputs>
				<input value="1" type="INTEGER" />
				<input
					value="All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it."
					type="STRING" />
			</inputs>
		</step>
		<step name="clickingoninline" method="clickOnInsertInline01" require="ArticlePreparation" />
		<step name="setHyperLink" method="insertHyperlink" require="Hyperlink" >
		<inputs>
				<input value="Scottish NSP " type="STRING" />
			</inputs>
		</step>	
		<step name="preparingtheArticle" method="storyPreparation"
			require="ArticlePreparation">
			<inputs>
				<input value="up" type="STRING" />
				<input value="30" type="INTEGER" />
				<input value="Automation Headline" type="STRING" />
				<input value="Automation Standfirst" type="STRING" />
				<input value="Automation onecolumnStandfirst" type="STRING" />
				<input value="Automation floorlineHeadline" type="STRING" />
				<input value="1" type="INTEGER" />
			</inputs>
		</step>
		<step name="closetemplatepage" method="close_window"
			require="TemplatePlan" />
		<step name="publishtheSlot" method="publish"
			require="EditorialPlan" />
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/exampel_testcase.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="ExampleTestCase">
	<steps>
		<step name="exampleMethodeWithParam" require="Login" method="doLogin">
			<inputs>
				<input value="10" type="INTEGER"/>
				<input value="33" type="INTEGER"/>
			</inputs>
			<expected>
				<result message="Page Planner should be openned" value="true" type="WINDOW"/>
				<result message="Article Should be published" value="true" element="cpi:headline" type="S3" feedType="article" />
			</expected>
		</step>
		<step name="exampleMethodeWithoutParams" require="PagePlanner" method="doSelectPublication"/>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/irish_slot_republish_witharticlechange.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="irishSlotRePublish"
	comments="Executing testcase in national Edition in News section Slot2">
	<steps>
		<!-- <step name="moveDowntoNewsSlot" method="editorialPageDown" require="EditorialPlan"> 
			<inputs> <input value="down" type="STRING" /> <input value="20" type="INTEGER" 
			/> </inputs> </step> -->
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="insertStory" method="create_article" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="clickCreateStoryBtn" method="storyCreateBtn" require="NewStory" />
		<step name="articleName" method="fileName" require="SaveStory">
			<inputs>
				<input value="SA_1_23_irish_Republish" type="STRING" />
			</inputs>
		</step>
		<step name="clickSaveAsBtn" method="saveasBtn" require="SaveStory"
			screenshot="true" />
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="performChannelCopy" method="createChannelCopy"
			require="ChannelCopy">

		</step>
		<step name="ArticleDescription" method="articleDescription"
			require="ArticlePreparation">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
				<input
					value="All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it."
					type="STRING" />
			</inputs>
		</step>
		<step name="inlineStoryPreparation" method="inlineStoryPreparation"
			require="ArticlePreparation">
			<inputs>
				<input value="up" type="STRING" />
				<input value="30" type="INTEGER" />
				<input value="SlotRepublish" type="STRING" />
			</inputs>
		</step>
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_1_23_irish_SlotRepublish*" type="STRING" />
			</inputs>
		</step>
		<step name="moveUp" method="mousewheeler" require="ArticlePreparation">
			<inputs>
				<input value="up" type="STRING" />
				<input value="20" type="INTEGER" />
			</inputs>
		</step>
		<step name="capturetheWindow" method="screenCapture" require="ArticlePreparation"
			screenshot="true" />
		<step name="saveTheArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan"
			screenshot="true">
			<expected>
				<result message="publishing the Slot" value="link"
					element="atom:link[@cpi:qualifier='articleMetaData']" type="S3"
					feedType="article" s3Content="true" />
			</expected>
		</step>
		<step name="OpenTheSelectedSlotAgaintoChangeTheArtilcle" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="openTheStory" method="open_article" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="enterTheTextinStandfirst" method="standfirst"
			require="ArticlePreparation">
			<inputs>
				<input value="Automation StandFirst" type="STRING" />
			</inputs>
		</step>
		<step name="capturetheWindowAfterPublish" method="screenCapture"
			require="ArticlePreparation" screenshot="true" />
		<step name="saveTheArticlewithChange" method="saveArticle"
			require="ArticlePreparation" />
		<step name="getArticleUUIDwithArticleChange" method="articleUUIDBtn"
			require="ArticlePreparation" />
		<step name="closetheArticlePreparationPagewithArticleChange"
			method="closeArticlePreparation" require="ArticlePreparation" />
		<step name="closetemplatepagewithUpdateArticle" method="close_window"
			require="TemplatePlan" />
		<step name="republishtheSlot" method="publish" require="EditorialPlan"
			screenshot="true">
			<expected>
				<result message="Republishing the Slot" value="link"
					element="atom:link[@cpi:qualifier='articleMetaData']" type="S3"
					feedType="article" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/st_irish_book_section_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="OpenBookSectionMetadataforIrishEdition" comments="Executing testcase in Irish edition in news book at News Cover Slot1. TC_ID: https://newsroom360.testrail.com/index.php?/tests/view/228459">
	<steps>
	<step name="selectTheSlot" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
	<step name="moveDowntoNewsSlot" method="editorialPageDown"
			require="EditorialPlan">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
			</inputs>
		</step>
	<step name="selectSlot" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
	<step name="OpenBookSectionSlotMetadata" method="stBookSectionMetadata" require="EditorialPlan"/>
	<step name="captureBookSectionSlotMetadata" method="screenCapture" require="EditorialPlan" screenshot="true"/>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/ps_782.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="FractionalDeeplinking">
	<steps>
		<step name="openselectedslot" method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot4" type="STRING" />
			</inputs>
		</step>
		<step name="createDeeplinking" method="createChildArticle"
			require="TemplatePlan" />
		<step name="clickingOnFractionalDeeplink" method="createFractionalDeeplink"
			require="NewStory" />
		<step name="clickingOnCreateButton" method="storyCreateBtn"
			require="NewStory" />
		<step name="articleName" method="fileName" require="SaveStory">
			<inputs>
				<input value="BS_Autom20" type="STRING" />
			</inputs>
		</step>
		<step name="clickSaveAsBtn" method="saveasBtn" require="SaveStory" />
		<step name="openingChildArticle" method="openchildarticle"
			require="TemplatePlan" />
		<step name="performChannelCopy" method="createChannelCopy"
			require="ChannelCopy" />
	<step name="preparingFractionalDeeplink" method="fractionalDeeplinkingImage"
			require="ArticlePreparation">
			<inputs>
				<input type="INTEGER" value="1" />
				<input value="" type="STRING" />
			</inputs>
		</step>
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan" />
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/tablet_metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="TabletMetadata"
	comments="Executing testcase in National Edition at Main Book in Front Section at Slot1. TC_ID: https://newsroom360.testrail.com/index.php?/tests/view/228282">
	<steps>
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="insertStory" method="create_article" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="clickCreateStoryBtn" method="storyCreateBtn" require="NewStory" />
		<step name="articleName" method="fileName" require="SaveStory">
			<inputs>
				<input value="SA_1_27_reg1_TabletMetadata" type="STRING" />
			</inputs>
		</step>
		<step name="clickSaveAsBtn" method="saveasBtn" require="SaveStory"
			screenshot="true" />
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="performChannelCopy" method="createChannelCopy"
			require="ChannelCopy">

		</step>
		<step name="ArticleDescription" method="articleDescription"
			require="ArticlePreparation">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
				<input
					value="All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it."
					type="STRING" />
			</inputs>
		</step>
		<step name="inlineStoryPreparation" method="inlineStoryPreparation"
			require="ArticlePreparation">
			<inputs>
				<input value="up" type="STRING" />
				<input value="30" type="INTEGER" />
				<input value="Tablet Metadata" type="STRING" />
			</inputs>
		</step>
		<step name="GetselectWindow" method="addImageCHPWithoutClosingQueryWindow"
			require="CHP">
			<inputs>
				<input value="BS_1_25_reg1_TemplateMetadata*" type="STRING" />
			</inputs>
		</step>
		<step name="saveArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" />
		<step name="Selectingthetablettab" method="selectingTablet"
			require="QuickMetadataTablet" />
		<step name="childArticlePanel" method="panelSettings" require="QuickMetadataTablet"
			screenshot="true">
			<inputs>
				<input value="0" type="INTEGER" />
			</inputs>
		</step>
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan"
			screenshot="true">
			<expected>
				<result message="Added PullQuote to the Article" value="link"
					element="atom:link[@cpi:qualifier='articleMetaData']" type="S3"
					feedType="article" />
			</expected>
		</step>
	</steps>
</testCase>


<!-- Preparing the testcase from CHP -->
<!-- <steps> <step name="slotSelection" method="slot" require="EditorialPlan"> 
	<inputs> <input value="slot4" type="STRING" /> </inputs> </step> <step name="gettingQuickAccess" 
	method="methodeQuery" require="TemplatePlan" /> <step name="fileName" method="dwpMethodeQuery" 
	require="NewSearchQuery"> <inputs> <input value="BS_HideHeadline_Story_6*" 
	type="STRING" /> <input value="articleSpec" type="STRING" /> </inputs> </step> 
	<step name="CheckingWindow" method="checkChannelCopyWindow" require="CHP" 
	/> <step name="preparingtheArticle" method="storyPreparationCHP" require="ArticlePreparation"> 
	<inputs> <input value="Hide Headline" type="STRING" /> <input value="Automation 
	Standfirst" type="STRING" /> <input value="Automation onecolumnStandfirst" 
	type="STRING" /> <input value="Automation floorlineHeadline" type="STRING" 
	/> </inputs> </step> <step name="GetselectWindow" method="addImageCHP" require="CHP"> 
	<inputs> <input value="BS_HideHeadline_Image_6*" type="STRING" /> </inputs> 
	</step> <step name="saveandPublishtheArticle" method="publishArticle" require="ArticlePreparation" 
	/> <step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" 
	/> <step name="Selectingthetablettab" method="selectingTablet" require="QuickMetadataTablet" 
	/> <step name="clickingHideHeadlinebutton" method="hideHeadline" require="QuickMetadataTablet" 
	/> <step name="publishtheArticlewhichhideheadline" method="publishArticle" 
	require="ArticlePreparation" /> <step name="getArticleUUID" method="articleUUIDBtn" 
	require="ArticlePreparation" /> <step name="closetheArticlePreparationPage" 
	method="closeArticlePreparation" require="ArticlePreparation" /> <step name="closetemplatepage" 
	method="close_window" require="TemplatePlan" /> <step name="navigatingtoTabPageFlow" 
	method="releasePage" require="EditorialPlan"> <inputs> <input value="slot4" 
	type="STRING" /> </inputs> </step> <step name="clickingontheStatus" method="tabPageFlow" 
	require="TabPageFlow"> <inputs> <input value="3" type="INTEGER" /> </inputs> 
	</step> <step name="navigatingtoWorkFlowWindow" method="workflowNational" 
	require="EditorialPlan" /> <step name="ChangingStatustoDone" method="editorialPlanDoneStatus" 
	require="EditorialWorkFlow" /> <expected> <result message="Validating the 
	standfirst" value="updated Automation Standfirst" element="cpi:standfirst/xhtml:div" 
	type="S3" feedType="article" /> </expected> </step> </steps> </testCase> -->
