=== jayvikramsharma1/jvs/mat-dashboard/schema/testcase.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT testCase (steps)>
<!ATTLIST testCase name CDATA #REQUIRED>
<!ATTLIST testCase comments CDATA #REQUIRED>
<!ELEMENT steps (step+)>
<!ELEMENT step (inputs*, expected*)>
<!ATTLIST step name CDATA #REQUIRED>
<!ATTLIST step require (Login|MoD|PagePlanner|Publication|EditorialPlan|TemplatePlan|NewStory|SaveStory|ChannelCopy|ArticlePreparation|QuickMetadataTablet|AssertInsertInline|NewSearchQuery|PagePlannerMetadata|ArticleImageMetadata|Formatting|EditorialWorkFlow|Hyperlink|TabPageFlow|CHP|SendToProduction|CHPFolder|InsertPages|PropertyWindow|SectionMetatadata|VideoStory|EditorialLogin|STEditionCreation|Confirmation) #REQUIRED>
<!ATTLIST step method CDATA #REQUIRED>
<!ATTLIST step screenshot (true|false) #IMPLIED>
<!ELEMENT inputs (input*)>
<!ELEMENT input EMPTY>
<!ATTLIST input value CDATA #REQUIRED>
<!ATTLIST input type (INTEGER|STRING|BOOLEAN) #REQUIRED>
<!ELEMENT expected (result*)>
<!ELEMENT result EMPTY>
<!ATTLIST result message CDATA #REQUIRED>
<!ATTLIST result value CDATA #REQUIRED>
<!ATTLIST result type (S3|WINDOW) #REQUIRED>
<!ATTLIST result feedType (edition|book|section|slot|article|image|articleMetadata|slotMetadata|imageMetadata|imagePositional) #REQUIRED>
<!ATTLIST result s3Content (true|false) #IMPLIED>
<!ATTLIST result element CDATA #REQUIRED>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/create_video_story.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="AddingVideoStory">
	<steps>
	 <step name="createVideoStory" method="createVideoStory" require="PagePlanner" />
	 <step name="clickCreateButton" method="storyCreateBtn" require="NewStory" />
	 <step name="saveVideoStory" method="saveFileAs" require="SaveStory">
			<inputs>
				<input value="SA_AutomationVideoStory1" type="STRING" />
			</inputs> 
		</step>
		<step name="enterTitle" method="titleHeadline" require= "VideoStory">
			<inputs>
				<input value="Automation" type="STRING" />
			</inputs> 
		</step>
		<step name="openQuickMetadata" method="quickmetadata" require="VideoStory" />
		<step name="enterEmbeddedCode" method="embeddeCode" require="VideoStory" />
		<step name="saveQuicMetadata" method="saveBtnDefault" require="QuickMetadataTablet" />
		<step name="openCandidateBrowser" method="openCandidateBrowser" require="ArticlePreparation" >
		<inputs>
				<input value="1" type="INTEGER" />
			</inputs>
		</step>
		<step name="videoStoryImage" method="candidateBrowserImage1" require="VideoStory" />
		<step name="saveandPublishtheArticle" method="saveArticle"
			require="ArticlePreparation" />
		<step name="closeArticlePreparationWindow" method="closevideoArticlePreparation"
			require="VideoStory" />
	 <!-- <step name="selectingPropertyUUID" method="gettingEditionPropertyUuid" require="PropertyWindow" >
	 <expected>
				<result message="Getting Edition Property" value="link"
					element="atom:link[@title='Main Book']" type="S3" feedType="edition" />
			</expected>
			</step> -->
			<!-- <inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs> 
		</step>
		<step name="GettingQuickAccessBar" method="getQuickAccessBar" require="ArticlePreparation" />
	    <step name="ClickingOnSearchIcon" method="clickOnSearchIcon" require="ArticlePreparation" /> 
	    <step name="GetVideoStory" method="fileName" require="NewSearchQuery" >
	    <inputs>
				<input value="BS_videostory0902" type="STRING" />
			</inputs>
	    </step>
	    <step name="ClickingOnOkbutton" method="okBtn" require="NewSearchQuery" />
	     <step name="ScrollingToInlineArea" method="mousewheeler" require="ArticlePreparation" >
	     <inputs>
				<input value="down" type="STRING" />
				<input value="18" type="INTEGER" />
			</inputs>
	    </step> 
	    <step name="DragVideoStory" method="dragAndDropVideoStory" require="ArticlePreparation" />
	     <step name="SaveAndCloseArticle" method="saveAndCloseStoryPreparation" require="ArticlePreparation" />
	    <step name="closetemplatepage" method="close_window"
			require="TemplatePlan" />
			<step name="publishtheSlot" method="publish"
			require="EditorialPlan" />  -->
	</steps>
	</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/st_blue_panel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="SundayTimesChildArticleBluePanel" comments="Executing the testcase in National Edition in Business Book at Business Cover section at Slot9. TC_ID: https://newsroom360.testrail.com/index.php?/tests/view/228316">
	<steps>
	 <step name="editorialPageDown" method="editorialPageDown"
			require="EditorialPlan">
			<inputs>
				<input value="down" type="STRING" />
				<input value="9" type="INTEGER" />
			</inputs>
		</step>
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="insertStory" method="create_article" require="TemplatePlan">
			<inputs>
				<input value="childArticle" type="STRING" />
			</inputs>
		</step>
		<step name="expandNational" method="stNationalExpand" require="NewStory">
			<inputs>
				<input value="4" type="INTEGER" />
			</inputs>
		</step>
		<step name="clickCreateStoryBtn" method="storyCreateBtn" require="NewStory" />
		<step name="articleName" method="fileName" require="SaveStory">
			<inputs>
				<input value="ST_SA_8_2_childArticleforBluePanel" type="STRING" />
			</inputs>
		</step>
		<step name="clickSaveAsBtn" method="saveasBtn" require="SaveStory" screenshot="true"/>
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="childArticle" type="STRING" />
			</inputs>
		</step>
		<step name="performChannelCopy" method="createChannelCopy"
			require="ChannelCopy" />
		<step name="entertheArticleText" method="articleDescription"
			require="ArticlePreparation">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
				<input
					value="All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it."
					type="STRING" />
			</inputs>
		</step>
		<step name="inlineStoryPreparation" method="inlineStoryPreparation"
			require="ArticlePreparation">
			<inputs>
				<input value="up" type="STRING" />
				<input value="30" type="INTEGER" />
				<input value="Child Article For Blue Panel" type="STRING" />
			</inputs>
		</step>
		<step name="getImageFromCHP" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_8_2_ST_BlueOveride*" type="STRING" />
			</inputs>
		</step>
		<step name="saveTheArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" />
		<step name="Selectingthetablettab" method="selectingTablet"
			require="QuickMetadataTablet" />
			<step name="childArticlePanel" method="panelSettings"
			require="QuickMetadataTablet" screenshot="true">
			<inputs>
				<input value="2" type="INTEGER" />
			</inputs>
		</step>
		<step name="clickingQuickMetadataSaveButton" method="saveBtnPosition"
			require="QuickMetadataTablet" />
			<step name="saveTheArticlewithchildpanel" method="saveArticle" require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_8_2_ST_Bluepanel*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_8_2_ST_Bluepanel*" type="STRING" />
			</inputs>
		</step>
		<step name="closetheArticlePreparationPageforMainArticle" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepageformainArticle" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="stPublish" require="EditorialPlan" screenshot="true">
		<expected>
				<result message="Panel should set as blue" value="bluePanel"
					element="cpi:style" type="S3" feedType="articleMetadata" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/st_irish_headlinetext_allignmentleft.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="SundayTimesIrishHeadlineTextAllignmentLeft"
	comments="Executing the test case in Business Book at Business Page Section at Slot4. TC_ID: https://newsroom360.testrail.com/index.php?/tests/view/228288">
	<steps>
		<!-- <step name="navigationtoStyleBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonStyle" method="stOtherNationalBooks" require="STEditionCreation" />
		<step name="slotSelectionStyleBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step> -->
		<step name="moveDowntoNewsSlot" method="editorialPageDown"
			require="EditorialPlan">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
			</inputs>
		</step>
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_1_15_st_irish_Headline_left*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_1_15_st_irish_Headline_left*" type="STRING" />
			</inputs>
		</step>
		<step name="saveArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" />
		<step name="Selectingthetablettab" method="selectingTablet"
			require="QuickMetadataTablet" />
		<step name="HeadlineTextAllignmentfromLefttoRight" method="headlineSpanDropDownPosition"
			require="QuickMetadataTablet" screenshot="true">
			<inputs>
				<input value="2" type="INTEGER" />
			</inputs>
		</step>
		<step name="clickingQuickMetadataSaveButton" method="saveBtnPosition"
			require="QuickMetadataTablet" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="stPublish" require="EditorialPlan"
			screenshot="true">
			<expected>
				<result message="Headline Text Allignment Should be Right"
					value="right" element="cpi:headlineTextAlignment" type="S3"
					feedType="articleMetadata" s3Content="true" />
			</expected>
		</step>
		<step name="openselectedslotforChangingingArticleheadlineAlignment"
			method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="OpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="saveArticleforleftallignment" method="saveArticle"
			require="ArticlePreparation" />
		<step name="OpenQuickAcess" method="getQuickAccessBar" require="ArticlePreparation" />
		<step name="openQuickMetadataforMetadataChange" method="quickmetadata"
			require="ArticlePreparation" />
		<step name="SelectingthetablettabforMetadataChange" method="selectingTablet"
			require="QuickMetadataTablet" />
		<step name="HeadlineTextAllignmentfromRighttoLeft" method="headlineSpanDropDownPositionUp"
			require="QuickMetadataTablet" screenshot="true">
			<inputs>
				<input value="2" type="INTEGER" />
			</inputs>
		</step>
		<step name="clickingQuickMetadataSaveButtonForLeftAlignment"
			method="saveBtnPosition" require="QuickMetadataTablet" />
		<step name="closetheArticlePreparationPagewithMetadatachanges"
			method="closeArticlePreparation" require="ArticlePreparation" />
		<step name="closetemplatepagewithMetadatachanges" method="close_window"
			require="TemplatePlan" />
		<step name="publishtheSlotwithMetadatachanges" method="stPublish"
			require="EditorialPlan" screenshot="true">
			<expected>
				<result message="Headline Text Allignment Should be Left"
					value="left" element="cpi:headlineTextAlignment" type="S3"
					feedType="articleMetadata" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/fractional_deeplinking.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="FractionalDeeplinking"
	comments="Executing the test case scotland section slot4 and 5">
	<steps>
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_Fractional_Deeplink_1*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_Fractional_Deeplink_1*" type="STRING" />
			</inputs>
		</step>
		<step name="saveTheArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan" />
		<step name="openselectedslotforFractionalDeeplink" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="createDeeplinking" method="createChildArticle"
			require="TemplatePlan" />
		<step name="clickingOnFractionalDeeplink" method="createFractionalDeeplink"
			require="NewStory" />
		<step name="clickingOnCreateButton" method="storyCreateBtn"
			require="NewStory" />
		<step name="articleName" method="fileName" require="SaveStory">
			<inputs>
				<input value="SA_Fractional_5" type="STRING" />
			</inputs>
		</step>
		<step name="clickSaveAsBtn" method="saveasBtn" require="SaveStory" />
		<step name="openingChildArticle" method="openchildarticle"
			require="TemplatePlan" />
		<step name="performChannelCopy" method="createChannelCopy"
			require="ChannelCopy" />
		<step name="navigatetoHypertextwindow" method="addingDeeplink"
			require="ArticlePreparation" />
		<step name="preparingFractionalDeeplink" method="insertHyperlink"
			require="Hyperlink">
			<inputs>
				<input value="Scottish National Party" type="STRING" />
			</inputs>
		</step>
		<step name="getImageFromCHP" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_Column_Percentage*" type="STRING" />
			</inputs>
		</step>
		<step name="closetheArticlePreparationPageFractionalDeeplink" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="gettingQuickAccesslinkedstory" method="methodeQuery" require="TemplatePlan" />
		<step name="fileNamelinkedstory" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_Fractional_Deeplink_2*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindowlinkedstory" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindowlinkedstory" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_Fractional_Deeplink_2*" type="STRING" />
			</inputs>
		</step>
		<step name="saveTheArticlelinkedstory" method="saveArticle" require="ArticlePreparation" />
		<step name="getArticleUUIDlinkedstory" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPagelinkedstory" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepagelinkedstory" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlotlinkedstory" method="publish" require="EditorialPlan" />
		<!-- <step name="closetemplatepage" method="close_window" require="TemplatePlan" 
			/> <step name="publishtheSlot" method="publish" require="EditorialPlan" /> -->
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/columnwidth3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="threeColumnWidth" comments="Executing the testcases in ireland at business section in slot6">
	<steps>
		<!-- <step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_3columnwidth*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_3columnwidth*" type="STRING" />
			</inputs>
		</step>
		<step name="saveandPublishtheArticle" method="saveArticle"
			require="ArticlePreparation" />
			<step name="MovingTopOftheArticle" method="mousewheeler"
			require="ArticlePreparation" >
			<inputs>
			<input value="up" type="STRING" />
				<input value="20" type="INTEGER" />
			</inputs>
		</step>
		<step name="performOneColumnWidth" method="columwidth" require="ArticlePreparation">
			<inputs>
				<input value="3" type="INTEGER" />
			</inputs>
		</step>
		<step name="MovingTopOftheArticletogetImageUUID" method="mousewheeler"
			require="ArticlePreparation" >
			<inputs>
		<input value="up" type="STRING" />
				<input value="20" type="INTEGER" />
			</inputs>
		</step>
		<step name="gettingImageUUID" method="imageUUIDBtn"
			require="ArticlePreparation">
		</step>
		<step name="closeStoryPreparationWindow" method="closeArticlePreparation"
			require="ArticlePreparation">
		</step>
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan"/> -->
			<step name="OpenTheSelectedSlottoAmendImagePosition"
			method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="opentheArticletoMakechangeinImagePosition" method="openarticle"
			require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="performOneColumnWidth" method="columwidth" require="ArticlePreparation" screenshot="true">
			<inputs>
				<input value="1" type="INTEGER" />
			</inputs>
		</step>
		<step name="MovingTopOftheArticletogetImageUUID" method="mousewheeler"
			require="ArticlePreparation" >
			<inputs>
		<input value="up" type="STRING" />
				<input value="20" type="INTEGER" />
			</inputs>
		</step>
		<step name="gettingImageUUID" method="imageUUIDBtn"
			require="ArticlePreparation">
		</step>
		<step name="closeStoryPreparationWindow" method="closeArticlePreparation"
			require="ArticlePreparation">
		</step>
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan">
			<expected>
				<result message="Image Column Width" value="1"
					element="cpi:widthInColumn" type="S3" feedType="imagePositional" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/disable_save_article.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="DisableSavingArticle" comments="Executing the testcase in Law Section at Slot1">
	<steps>
		<!-- <step name="movedown" method="editorialPageDown" require="EditorialPlan">
			<inputs>
				<input value="down" type="STRING" />
				<input value="30" type="INTEGER" />
			</inputs>
		</step> -->
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_Metadata_true*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_Metadata_true*" type="STRING" />
			</inputs>
		</step>
		<step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" />
		<step name="selectingTheTabletTab" method="selectingTablet"
			require="QuickMetadataTablet" />

		<step name="clickOnDisableSavingArticle" method="disableSavingArticle"
			require="QuickMetadataTablet">
		</step>
		<step name="savetheChangesDoneinQuickMetadata" method="saveBtnPosition" require="QuickMetadataTablet" />
		<step name="saveandPublishtheArticle" method="saveArticle"
			require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan">
		<expected>
				<result message="Saving Article Should hide" value="true"
					element="cpi:hideSaving" type="S3" feedType="articleMetadata" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/chp_story_comments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="ChpStoriesComments">
	<steps>
		<!-- <step name="clickingOnSearchCHP" method="chpQuery" require="PagePlanner" />
		<step name="querySelect" method="quickCHPQuery" require="CHP">
			<inputs>
				<input value="story" type="STRING" />
			</inputs>
		</step> -->
		<!-- <step name="searchingStory" method="storySearch" require="CHP">
			<inputs>
				<input value="comments" type="STRING" />
			</inputs>
		</step>
		<step name="clickonStory01" method="sendToProduction01" require="PagePlanner" />

		<step name="sendToProductionStory01" method="sendToProduction"
			require="SendToProduction">
			<inputs>
				<input value="SA_hide_navigation_Slot_1" type="STRING" />
			</inputs>
		</step> -->

		<step name="clickonStory02" method="sendtoProduction02" require="PagePlanner" />
		<step name="sendToProductionStory02" method="sendToProduction"
			require="SendToProduction">
			<inputs>
				<input value="SA_masthead_style_Slot_1" type="STRING" />
			</inputs>
		</step>
		<step name="searchForPictures" method="pictureSearch" require="CHP" />
		<step name="clickonImage01" method="sendToProduction01" require="PagePlanner" />

		<step name="sendToProductionImage01" method="sendToProduction"
			require="SendToProduction">
			<inputs>
				<input value="BS_hide_navigation_Image_2" type="STRING" />
			</inputs>
		</step>
		<step name="clickonImage02" method="sendtoProduction02" require="PagePlanner" />
		<step name="sendToProductionImage02" method="sendToProduction"
			require="SendToProduction">
			<inputs>
				<input value="BS_masthead_style_Image_2" type="STRING" />
			</inputs>
		</step>
	</steps>
	</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/reordering_page.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="ReoderingThePages"
	comments="Swapping the Slots in Business Section. TC_ID: https://newsroom360.testrail.com/index.php?/tests/view/228267">
	<steps>
		<!-- <step name="editorialPageDown" method="editorialPageDown" require="EditorialPlan"> 
			<inputs> <input value="down" type="STRING" /> <input value="20" type="INTEGER" 
			/> </inputs> </step> <step name="newsSlotSelection" method="slot" require="EditorialPlan"> 
			<inputs> <input value="newsSlot3" type="STRING" /> </inputs> </step> <step 
			name="allContent" method="allContent" require="EditorialPlan" /> <step name="selectTheSlot" 
			method="selectSlot" require="EditorialPlan"> <inputs> <input value="slot2" 
			type="STRING" /> </inputs> </step> <step name="editorialPageDown" method="editorialPageDown" 
			require="EditorialPlan"> <inputs> <input value="up" type="STRING" /> <input 
			value="30" type="INTEGER" /> </inputs> </step> <step name="captureScreen" 
			method="screenCapture" require="EditorialPlan" screenshot="true" /> <step 
			name="selectdifferentslot" method="selectSlot" require="EditorialPlan"> <inputs> 
			<input value="slot1" type="STRING" /> </inputs> </step> -->
			<step name="selectingUnslot" method="unslot" require="EditorialPlan">
		</step>
		<step name="selectSlot" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="editorialPageUp" method="editorialPageDown" require="EditorialPlan">
			<inputs>
				<input value="up" type="STRING" />
				<input value="35" type="INTEGER" />
			</inputs>
		</step>
		<step name="selectBusinessSectionslot" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="savePagePlan" method="saveArticle" require="EditorialPlan" />
		<step name="publishtheSection" method="publishSlotUUID" require="EditorialPlan"
			screenshot="true">
			<expected>
				<result message="Validating before swapping" value="Business"
					element="cpi:sectionname" type="S3" feedType="section" s3Content="true" />
			</expected>
		</step> 
		<step name="editorialPagedownagain" method="editorialPageDown"
			require="EditorialPlan">
			<inputs>
				<input value="down" type="STRING" />
				<input value="10" type="INTEGER" />
			</inputs>
		</step>
		<step name="captureScreen" method="screenCapture" require="EditorialPlan"
			screenshot="true" />
		<step name="swapslots" method="reorderingPages" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="swapslots1" method="reorderingPages2" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="swapslots2" method="reorderingPages3" require="EditorialPlan">
			<inputs>
				<input value="slot3" type="STRING" />
			</inputs>
		</step>
		<step name="captureScreenafterSwapping" method="screenCapture"
			require="EditorialPlan" screenshot="true" />
		<step name="slotSelectionMainBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="editorialPageupagain" method="editorialPageDown"
			require="EditorialPlan">
			<inputs>
				<input value="up" type="STRING" />
				<input value="10" type="INTEGER" />
			</inputs>
		</step>
		<step name="selectBusinessSlotAgain" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="savePagePlanafterSwapping" method="saveArticle"
			require="EditorialPlan" />
		<step name="publishtheSectionafterSwapping" method="publishSlotUUID"
			require="EditorialPlan" screenshot="true">
			<expected>
				<result message="Validating after swapping" value="Business"
					element="cpi:sectionname" type="S3" feedType="section" />
			</expected>
		</step>
		<step name="editorialPagedownfornextcase" method="editorialPageDown"
			require="EditorialPlan">
			<inputs>
				<input value="down" type="STRING" />
				<input value="30" type="INTEGER" />
			</inputs>
		</step>
	</steps>
</testCase>
