=== jayvikramsharma1/jvs/mat-dashboard/schema/testcase.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT testCase (steps)>
<!ATTLIST testCase name CDATA #REQUIRED>
<!ATTLIST testCase comments CDATA #REQUIRED>
<!ELEMENT steps (step+)>
<!ELEMENT step (inputs*, expected*)>
<!ATTLIST step name CDATA #REQUIRED>
<!ATTLIST step require (Login|MoD|PagePlanner|Publication|EditorialPlan|TemplatePlan|NewStory|SaveStory|ChannelCopy|ArticlePreparation|QuickMetadataTablet|AssertInsertInline|NewSearchQuery|PagePlannerMetadata|ArticleImageMetadata|Formatting|EditorialWorkFlow|Hyperlink|TabPageFlow|CHP|SendToProduction|CHPFolder|InsertPages|PropertyWindow|SectionMetatadata|VideoStory|EditorialLogin|STEditionCreation|Confirmation) #REQUIRED>
<!ATTLIST step method CDATA #REQUIRED>
<!ATTLIST step screenshot (true|false) #IMPLIED>
<!ELEMENT inputs (input*)>
<!ELEMENT input EMPTY>
<!ATTLIST input value CDATA #REQUIRED>
<!ATTLIST input type (INTEGER|STRING|BOOLEAN) #REQUIRED>
<!ELEMENT expected (result*)>
<!ELEMENT result EMPTY>
<!ATTLIST result message CDATA #REQUIRED>
<!ATTLIST result value CDATA #REQUIRED>
<!ATTLIST result type (S3|WINDOW) #REQUIRED>
<!ATTLIST result feedType (edition|book|section|slot|article|image|articleMetadata|slotMetadata|imageMetadata|imagePositional) #REQUIRED>
<!ATTLIST result s3Content (true|false) #IMPLIED>
<!ATTLIST result element CDATA #REQUIRED>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/st_create_edition.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="STEditionCreationNational"
	comments="Executing testcase for creating edition in national">
	<steps>
		<step name="ExpandingNationalPublishing" method="nationalPlanExtend"
			require="EditorialPlan" />
		<step name="slotSelectionNewsBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforNews" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforNewsSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="slotSelection" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="clickingOnSportsBook" method="stSportsNational"
			require="STEditionCreation" />
		<step name="slotSelectionSportsBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforSports" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforSportsSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="slotSelectionSports" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoMagazineBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonMagazine" method="stOtherNationalBooks"
			require="STEditionCreation" />
		<step name="slotSelectionMagazineBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforMagazine" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforMagazineSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="slotSelectionMagazine" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoBuisnessBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonBuisness" method="stOtherNationalBooks"
			require="STEditionCreation" />
		<step name="slotSelectionBuisnessBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforBuisness" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforBuisnessSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoNewsReviewBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonNewsReview" method="stOtherNationalBooks"
			require="STEditionCreation" />
		<step name="slotSelectionNewsReviewBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforNewsReview" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforNewsReviewSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoCultureBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonCulture" method="stOtherNationalBooks"
			require="STEditionCreation" />
		<step name="slotSelectionCultureBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforCulture" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforCultureSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoStyleBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonStyle" method="stOtherNationalBooks" require="STEditionCreation" />
		<step name="slotSelectionStyleBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforStyle" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforStyleSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoTravelBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonTravel" method="stTravelNationalBooks"
			require="STEditionCreation" />
		<step name="slotSelectionTravelBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforTravel" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforTravelSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoNews" method="leftNavigation" require="STEditionCreation" />
		<step name="clickingOnNewsBook" method="stNewsNational" require="STEditionCreation" />
		<step name="navigateToWorkflowWindow" method="workflowNational"
			require="EditorialPlan" />
		<step name="changeTheEditionToInprogress" method="editorialPlanInProgress"
			require="EditorialWorkFlow" />
		<step name="openPropertyWindow" method="propertyWindow" require="EditorialPlan" />
		<step name="selectingPropertyUUID" method="gettingEditionPropertyUuid"
			require="PropertyWindow">
			<expected>
				<result message="vaidating News Book is Created" value="link"
					element="atom:link[@title='News']" type="S3" feedType="edition" />
				<result message="vaidating Sport Book is Created" value="link"
					element="atom:link[@title='Sport']" type="S3" feedType="edition" />
				<result message="vaidating Magazine Book is Created" value="link"
					element="atom:link[@title='Magazine']" type="S3" feedType="edition" />
				<result message="vaidating Buisness Book is Created" value="link"
					element="atom:link[@title='Business']" type="S3" feedType="edition" />
				<result message="vaidating News Review Book is Created"
					value="link" element="atom:link[@title='News Review']" type="S3"
					feedType="edition" />
				<result message="vaidating Style Book is Created" value="link"
					element="atom:link[@title='Style']" type="S3" feedType="edition" />
				<result message="vaidating Travel Book is Created" value="link"
					element="atom:link[@title='Travel']" type="S3" feedType="edition" />
				<result message="vaidating Culture Book is Created" value="link"
					element="atom:link[@title='Culture']" type="S3" feedType="edition" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/st_create_edition_ireland.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="STEditionCreationIreland"  comments="Creating edition for Irishedition in Sundaytimes. TC_ID:https://newsroom360.testrail.com/index.php?/tests/view/228527">
	<steps>
		<step name="ExpandingIrishPublishing" method="irishPlanExtend"
			require="EditorialPlan" />
		<step name="ClcikingOnIrishMainBook" method="irishMainbookBtn"
			require="EditorialPlan" />
		<step name="slotSelectionNewsBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforNews" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforNewsSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="slotSelectionNews" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="clickingOnSportsBook" method="stSportsIreland"
			require="STEditionCreation" />
		<step name="slotSelectionSportsBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforSports" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforSportsSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="slotSelectionSports" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoMagazineBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonMagazine" method="stOtherIrelandBooks"
			require="STEditionCreation" />
		<step name="slotSelectionMagazineBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforMagazine" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforMagazineSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="slotSelectionMagazine" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot1" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoBuisnessBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonBuisness" method="stOtherIrelandBooks"
			require="STEditionCreation" />
		<step name="slotSelectionBuisnessBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforBuisness" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforBuisnessSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoNewsReviewBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonNewsReview" method="stOtherIrelandBooks"
			require="STEditionCreation" />
		<step name="slotSelectionNewsReviewBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforNewsReview" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforNewsReviewSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoSDSunday" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonSDSunday" method="stOtherIrelandBooks"
			require="STEditionCreation" />
		<step name="slotSelectionSDSundayBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforSDSunday" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforSDSundaySlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoCultureBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonCulture" method="stOtherIrelandBooks"
			require="STEditionCreation" />
		<step name="slotSelectionCultureBook" method="selectSlot"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforCulture" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforCultureSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoStyleBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonStyle" method="stOtherIrelandBooks" require="STEditionCreation" />
		<step name="slotSelectionStyleBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforStyle" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforStyleSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoTravelBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonTravelBook" method="stTravelIrelandBooks" require="STEditionCreation" />
		<step name="slotSelectionTravelBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforTravelBook" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforTravelBookSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoSundayClubBook" method="rightNavigation"
			require="STEditionCreation" />
		<step name="clickonSundayClub" method="stTravelIrelandBooks"
			require="STEditionCreation" />
		<step name="slotSelectionSundayClubBook" method="selectSlot" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="selectingallSlotforSundayClub" method="selectAllSlot"
			require="EditorialPlan" />
		<step name="creatingtheSlotDWPforSundayClubSlot" method="slotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="navigationtoNews" method="leftNavigation" require="STEditionCreation" />
		<step name="clickingOnNewsBook" method="stNewsIreland" require="STEditionCreation" />
		<step name="NavigateToWorkflowWindow" method="workflowIrish"
			require="EditorialPlan" />
		<step name="ChangeTheEditionToInprogress" method="editorialPlanInProgress"
			require="EditorialWorkFlow" />
		<step name="openPropertyWindow" method="propertyWindowIrish"
			require="EditorialPlan" />
		<step name="selectingPropertyUUID" method="gettingEditionPropertyUuid"
			require="PropertyWindow">
			<expected>
				<result message="vaidating News Book is Created"
					value="link" element="atom:link[@title='News']" type="S3" feedType="edition" />
				<result message="vaidating Sport Book is Created" value="link"
					element="atom:link[@title='Sport']" type="S3" feedType="edition" />
				<result message="vaidating Magazine Book is Created"
					value="link" element="atom:link[@title='Magazine']" type="S3"
					feedType="edition" />
				<result message="vaidating Buisness Book is Created" value="link"
					element="atom:link[@title='Business']" type="S3" feedType="edition" />
				<result message="vaidating News Review Book is Created"
					value="link" element="atom:link[@title='News Review']" type="S3"
					feedType="edition" />
				<result message="vaidating Style Book is Created" value="link"
					element="atom:link[@title='Style']" type="S3" feedType="edition" />
				<result message="vaidating Travel Book is Created"
					value="link" element="atom:link[@title='Travel']" type="S3"
					feedType="edition" />
				<result message="vaidating Culture Book is Created" value="link"
					element="atom:link[@title='Culture']" type="S3" feedType="edition" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/testcases/tablet/st_irish_headlinespan2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="SundayTimesIrishHeadlineSpanText2"
	comments="Executing the testcase in Irish Edition Sports book at Sport/Sport Section at Slot5. TC_ID: https://newsroom360.testrail.com/index.php?/tests/view/228263">
	<steps>
		<step name="OpenTheSelectedSlot" method="openSlotSelection"
			require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="gettingQuickAccess" method="methodeQuery" require="TemplatePlan" />
		<step name="fileName" method="dwpMethodeQuery" require="NewSearchQuery">
			<inputs>
				<input value="SA_1_30_ST_irishheadlinspan2*" type="STRING" />
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="CheckingWindow" method="checkChannelCopyWindow"
			require="CHP" />
		<step name="GetselectWindow" method="addImageCHP" require="CHP">
			<inputs>
				<input value="BS_1_30_ST_irish_headlinspan2*" type="STRING" />
			</inputs>
		</step>
		<step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" />
		<step name="Selectingthetablettab" method="selectingTablet"
			require="QuickMetadataTablet" />
		<step name="selectingHeadlineSpanText2" method="headlineSpanDropDownnumber"
			require="QuickMetadataTablet" screenshot="true">
			<inputs>
				<input value="1" type="INTEGER" />
			</inputs>
		</step>
		<step name="clickingQuickMetadataSaveButton" method="saveBtnPosition"
			require="QuickMetadataTablet" />
		<step name="saveTheArticle" method="saveArticle" require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="publishtheSlot" method="stPublish" require="EditorialPlan"
			screenshot="true">
			<expected>
				<result message="Article Headline Should hide" value="2"
					element="cpi:headlineSpan" type="S3" feedType="articleMetadata" />
			</expected>
		</step>
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/dynamic_url.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="DynamicURL"
	comments="Executing the test case times2 Book in Times2 section slot1">
	<steps>
		<step name="openShapeLibrary" method="shapeLibrary" require="EditorialPlan" />
		<step name="SelecttheTemplate" method="templatePattern" require="EditorialPlan">
			<inputs>
				<input value="1" type="INTEGER" />
			</inputs>
		</step>
		<step name="enterandSearchthetemplateDesign" method="searchTemplateDesign"
			require="EditorialPlan">
			<inputs>
				<input value="TT_TD_Dynamic_url_Root_article_Mark" type="STRING" />
			</inputs>
		</step>
		<step name="movetheTemplateinSlot1" method="tdSlot2" require="EditorialPlan" />
		<step name="openselectedslot" method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot2" type="STRING" />
			</inputs>
		</step>
		<step name="createanArticle" method="create_article" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="clickCreatebutton" method="storyCreateBtn" require="NewStory" />
		<step name="performSaveAsfunction" method="saveFileAs" require="SaveStory">
			<inputs>
				<input value="SA_DynamicUrl_4" type="STRING" />
			</inputs>
		</step>
		<step name="opentheArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step>
		<step name="performChannelCopyaction" method="createChannelCopy"
			require="ChannelCopy" />
		<step name="clickAddRelatedLink" method="addRelatedLink" require="ArticlePreparation" />
		<step name="Movedownforpreparearticlelink" method="mousewheeler"
			require="ArticlePreparation">
			<inputs>
				<input value="down" type="STRING" />
				<input value="12" type="INTEGER" />
			</inputs>
		</step>
		<step name="openHyperLink" method="insertRelatedLink" require="ArticlePreparation">
		</step>
		<step name="clickandentertheWebAddress" method="clickOnTextAreawebUrl"
			require="Hyperlink">
			<inputs>
			<input value="facebook" type="STRING" />
				<input value="http://www.facebook.com" type="STRING" />
			</inputs>
		</step>
		<step name="clickokBtn" method="clickOKBtn" require="Hyperlink"/>
			<step name="Moveup" method="mousewheeler" require="ArticlePreparation">
				<inputs>
					<input value="up" type="STRING" />
					<input value="15" type="INTEGER" />
				</inputs>
			</step>
			<step name="ArticleDescription" method="articleDescription"
				require="ArticlePreparation">
				<inputs>
					<input value="down" type="STRING" />
					<input value="10" type="INTEGER" />
					<input
						value="All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it. All those things which falls under the cognizance of man might very likely be mutually related in the same fashion and there can be nothing so remote that we cannot reach to it."
						type="STRING" />
				</inputs>
			</step>
			<step name="inlineStoryPreparation" method="inlineStoryPreparation"
				require="ArticlePreparation">
				<inputs>
					<input value="up" type="STRING" />
					<input value="30" type="INTEGER" />
					<input value="Dynamic Url" type="STRING" />
				</inputs>
			</step>
			<step name="getImageFromCHP" method="addImageCHP" require="CHP">
				<inputs>
					<input value="BS_Column_Percentage*" type="STRING" />
				</inputs>
			</step>
			<step name="saveTheArticlelinkedstory" method="saveArticle"
				require="ArticlePreparation" />
			<step name="getArticleUUIDlinkedstory" method="articleUUIDBtn"
				require="ArticlePreparation" />
			<step name="closetheArticlePreparationPagelinkedstory" method="closeArticlePreparation"
				require="ArticlePreparation" />
			<step name="closetemplatepagelinkedstory" method="close_window"
				require="TemplatePlan" />
			<step name="publishtheSlotlinkedstory" method="publish" require="EditorialPlan" />
	</steps>
</testCase>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/testcases/tablet/child_article_blue_panel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE testCase SYSTEM "../../schema/testcase.dtd">
<testCase name="ChildArticleBluePanel">
	<steps>
		<!-- <step name="openselectedslot" method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot4" type="STRING" />
			</inputs>
		</step>
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="articleSpec" type="STRING" />
			</inputs>
		</step> -->
		<step name="openselectedslot" method="openSlotSelection" require="EditorialPlan">
			<inputs>
				<input value="slot4" type="STRING" />
			</inputs>
		</step>
		<step name="launchCandidateBrowser" method="candidateBrowser"
			require="TemplatePlan">
		</step>
		<step name="addStoryToChildArticle" method="dragExistingStory" require="TemplatePlan">
		</step>
		<step name="clickOpenArticle" method="openarticle" require="TemplatePlan">
			<inputs>
				<input value="childArticle" type="STRING" />
			</inputs>
		</step>
		<step name="openQuickMetadata" method="quickmetadata" require="ArticlePreparation" />
		<step name="Selectingthetablettab" method="selectingTablet"
			require="QuickMetadataTablet" />
		<step name="childArticlePanel" method="panelSettings"
			require="QuickMetadataTablet" />
		<step name="saveandPublishtheArticle" method="publishArticle"
			require="ArticlePreparation" />
		<step name="getArticleUUID" method="articleUUIDBtn" require="ArticlePreparation" />
		<step name="closetheArticlePreparationPage" method="closeArticlePreparation"
			require="ArticlePreparation" />
		<step name="closetemplatepage" method="close_window" require="TemplatePlan" />
		<step name="navigatingtoTabPageFlow" method="releasePage"
			require="EditorialPlan">
			<inputs>
				<input value="slot4" type="STRING" />
			</inputs>
		</step>
		<step name="clickingontheStatus" method="tabPageFlow" require="TabPageFlow">
			<inputs>
				<input value="3" type="INTEGER" />
			</inputs>
		</step>
		<step name="navigatingtoWorkFlowWindow" method="workflowNational"
			require="EditorialPlan" />
		<step name="ChangingStatustoDone" method="editorialPlanDoneStatus"
			require="EditorialWorkFlow" />
		<step name="publishtheSlot" method="publish" require="EditorialPlan">
		<expected>
				<result message="Panel should set as blue" value="bluePanel"
					element="cpi:style" type="S3" feedType="articleMetadata" />
			</expected>
		</step>
	</steps>
</testCase>
