=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/schema/env.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT settings (default, dev, si, stage, uat, prod, methode, s3URL, s3Bucket, s3ApiKey, s3ApiSecret, s3MediaPath, s3ReportPath, articleFeed, slotFeed, bookFeed, sectionFeed, editionFeed, imageFeed, articleMetadataFeed, slotMetadataFeed, imageMetadataFeed, imagePositionalFeed )>
<!ELEMENT default  (#PCDATA)>
<!ATTLIST default channel CDATA #REQUIRED>
<!ATTLIST default title CDATA #REQUIRED>
<!ATTLIST default env CDATA #REQUIRED>
<!ELEMENT dev (#PCDATA)>
<!ATTLIST dev username CDATA #REQUIRED>
<!ATTLIST dev password CDATA #REQUIRED>
<!ELEMENT si (#PCDATA)>
<!ATTLIST si username CDATA #REQUIRED>
<!ATTLIST si password CDATA #REQUIRED>
<!ELEMENT stage (#PCDATA)>
<!ATTLIST stage username CDATA #REQUIRED>
<!ATTLIST stage password CDATA #REQUIRED>
<!ELEMENT uat (#PCDATA)>
<!ATTLIST uat username CDATA #REQUIRED>
<!ATTLIST uat password CDATA #REQUIRED>
<!ELEMENT prod (#PCDATA)>
<!ATTLIST prod username CDATA #REQUIRED>
<!ATTLIST prod password CDATA #REQUIRED>
<!ELEMENT methode (#PCDATA)>
<!ATTLIST methode path CDATA #REQUIRED>
<!ELEMENT s3URL (#PCDATA)>
<!ATTLIST s3URL path CDATA #REQUIRED>
<!ELEMENT s3Bucket (#PCDATA)>
<!ELEMENT s3ApiKey (#PCDATA)>
<!ELEMENT s3ApiSecret (#PCDATA)>
<!ELEMENT s3MediaPath (#PCDATA)>
<!ELEMENT s3ReportPath (#PCDATA)>
<!ELEMENT articleFeed (#PCDATA)>
<!ATTLIST articleFeed path CDATA #REQUIRED>
<!ELEMENT slotFeed (#PCDATA)>
<!ATTLIST slotFeed path CDATA #REQUIRED>
<!ELEMENT bookFeed (#PCDATA)>
<!ATTLIST bookFeed path CDATA #REQUIRED>
<!ELEMENT sectionFeed (#PCDATA)>
<!ATTLIST sectionFeed path CDATA #REQUIRED>
<!ELEMENT editionFeed (#PCDATA)>
<!ATTLIST editionFeed path CDATA #REQUIRED>
<!ELEMENT imageFeed (#PCDATA)>
<!ATTLIST imageFeed path CDATA #REQUIRED>
<!ELEMENT articleMetadataFeed (#PCDATA)>
<!ATTLIST articleMetadataFeed path CDATA #REQUIRED>
<!ELEMENT slotMetadataFeed (#PCDATA)>
<!ATTLIST slotMetadataFeed path CDATA #REQUIRED>
<!ELEMENT imageMetadataFeed (#PCDATA)>
<!ATTLIST imageMetadataFeed path CDATA #REQUIRED>
<!ELEMENT imagePositionalFeed (#PCDATA)>
<!ATTLIST imagePositionalFeed path CDATA #REQUIRED>

=== jayvikramsharma1/jvs/mat-dashboard/target/jfx/app/config/env.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "../schema/env.dtd">
<settings>
	<default channel="tablet" title="sundaytimes" env="si" /> <!-- //sunday_times//sun//times-->
	<dev username="Testing" password="testpasssfsdjkfhsdklfjsdklj" />
	<si username="testuserdasdasdasd" password="testpasssdasdasdasd" />
	<stage username="testuser" password="testpass" />
	<uat username="testuser" password="testpass" />
	<prod username="testuser" password="testpass" />
	<methode path="C:\\Program Files\\EidosMedia\\Methode\\bin\\Methode.exe"/>
	<s3URL path="https://nu-cps-hub-dev-assets.s3.amazonaws.com/methode/"/>
	<s3Bucket>nu-cps-hub-dev-assets</s3Bucket>
	<s3ApiKey>APi</s3ApiKey>
	<s3ApiSecret>secret</s3ApiSecret>
	<s3MediaPath>methode/si/automation-dashboard/images/</s3MediaPath>
	<s3ReportPath>methode/si/automation-dashboard/report/</s3ReportPath>
	<articleFeed path="/articles/"/>
	<slotFeed path="/slots/"/>
	<bookFeed path="/books/"/>
	<sectionFeed path="/sections/"/>
	<editionFeed path="/editions/ljkljkljk"/>
	<imageFeed path="/assets/"/>
	<articleMetadataFeed path="/metadata/"/>
	<slotMetadataFeed path="/metadata/"/>
	<imageMetadataFeed path="/metadata/"/>
	<imagePositionalFeed path ="/positional/"/>
</settings>
